### ISSUE TITLE
problems running schedule with crystal 0.23.0

### ISSUE THREAD

**Issue by renich** [hugoabonizio/schedule.cr#1]
Hello,

Here's what I tried on a brand new project.

``` bash
# init app
crystal init app test
cd test

# add dependencies
cat << 'EOF' >> shard.yml
dependencies:
  schedule:
    github: hugoabonizio/schedule.cr
EOF

# get deps
crystal deps

# code
cat << 'EOF' > src/test.cr
require "schedule"

# Print "Hello!" each 2 seconds
Schedule.every(2.seconds) do
  puts "Hello!"
end

# Set a default exception handler
Schedule.exception_handler do |ex|
  puts "Exception recued! #{ex.message}"
end
EOF

# run
crystal run src/test.cr
```
The output was:
```
$ crystal run src/test.cr
Error in src/test.cr:9: wrong number of block arguments (given 1, expected 0)

Schedule.exception_handler do |ex|
         ^~~~~~~~~~~~~~~~~
```

**Comment by hugoabonizio** [comment]
Hello, @renich! Thank you for reporting this issue :smile:

This was fixed in d35c623

I turned the ```Schedule.exception_handler``` into a syntax sugar to define the ```exception_handler``` class property, and you can set this directly as the example bellow too:

```crystal
Schedule.exception_handler = ->(ex : Exception) do
  puts "Exception recued! #{ex.message}"
end
```

On the examples inside examples folder I added a ```sleep``` call at the bottom, because if you are running only the Schedule you won't see any result because the blocks are spawned in another fiber concurrently. So the whole test file would be:

```crystal
# Print "Hello!" each 2 seconds
Schedule.every(2.seconds) do
  raise "Hello!"
end

# Set a default exception handler
Schedule.exception_handler do |ex|
  puts "Exception recued! #{ex.message}"
end

sleep
```

If you have any other doubts I'm glad to answer.

**Comment by renich** [comment]
Adding the sleep at the bottom works fine. Thanks! Maybe it would be good to document that last bit about configuring the exception handler.

Here's what works, for the sake of completeness. 

```
# init app
crystal init app test
cd test

# add dependencies
cat << 'EOF' >> shard.yml
dependencies:
  schedule:
    github: hugoabonizio/schedule.cr
EOF

# get deps
crystal deps

# code
cat << 'EOF' > src/test.cr
require "schedule"

# Print "Hello!" each 2 seconds
Schedule.every(2.seconds) do
  puts "Hello!"
end

# Set a default exception handler
Schedule.exception_handler do |ex|
  puts "Exception recued! #{ex.message}"
end

sleep
EOF

# run
crystal run src/test.cr
```

**Comment by hugoabonizio** [comment]
I added a note about it on readme: [Exception handlers](https://github.com/hugoabonizio/schedule.cr/blob/master/README.md#exception-handlers). But the documentation is lacking right now, I'll work on that next few days.

**Comment by renich** [comment]
Thanks a lot, man. Feel free to close this ticket, then. :)
