### ISSUE TITLE
Broken in Crystal 0.33

### ISSUE THREAD

**Issue by iambudi** [hugoabonizio/schedule.cr#14]
`Time.new`, `Time.now`, `Time.utc_now` are deprecated and removed in crystal 0.33. I guess we have to use `Time.local` or `Time.utc`?

```bash
In lib/schedule/src/schedule.cr:95:25

 95 | current_time = Time.now
                          ^--
Error: undefined method 'now' for Time.class
```

**Comment by hugoabonizio** [comment]
@iambudi @lebron32rus @philipp-classen sorry for the delay, I've been quite busy. PR #15 fixes this issue.
