### ISSUE TITLE
run tasks on a specific day of the week

### ISSUE THREAD

**Issue by tonyvince** [hugoabonizio/schedule.cr#3]
Is there a way that I can run tasks on a specific day of the week, say every Tuesday?
I have been using the[ whenever gem](https://github.com/javan/whenever) and it has a nice option to do that
```ruby
every :sunday, :at => '12pm' do # Use any day of the week or :weekend, :weekday
  runner "Task.do_something_great"
end
```

**Comment by hugoabonizio** [comment]
Hi @tonyvince, thank you for the suggestion!

I think it's a nice feature and have plans to implement it sometime, but if you want to tackle on this, feel free to send a PR! :smile:

**Comment by hugoabonizio** [comment]
@tonyvince There's a [new release](https://github.com/hugoabonizio/schedule.cr/releases/tag/v0.2.0) that includes this feature, do you wanna take a look? :smiley: 

Now it's possible to do things like this:

```crystal
Schedule.every(:day, "16:00:00") do
  puts "Good Afternoon!"
end
```

And use days of the week, as you suggested:

```crystal
Schedule.every(:sunday, "16:00:00") do
  puts "House Keeping"
end
```
