### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [hugoabonizio/schedule.cr#8]
Hello,

I've checked your project and it either:

* Has specs failed with the latest Crystal (0.26.1)
* Has no any specs to run so it cannot be validated to be up to date
* Has the latest commit dated more than a year ago

Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by hugoabonizio** [comment]
Hi Vlad!

Thanks for pointing me that. I tackled this issue on #9. This should be fixed for Crystal 0.26.1 now.

Your automated script can be useful on initiatives like @bcardiff's [test-ecosystem](https://github.com/bcardiff/test-ecosystem)!

Thank you :bowtie:

**Comment by bcardiff** [comment]
@hugoabonizio I wrote https://crystal-lang.org/2018/09/04/using-circleci-2.0-for-your-crystal-projects.html it can serve as a starting point to add CircleCI in this project with nightly build support.

Great initiative @vladfaust to keep things up to date 🙇

**Comment by vladfaust** [comment]
Alright! My pleasure :smile: BTW, Travis also supports cron builds!

**Comment by bcardiff** [comment]
yes but the problem with travis is that the nightly repos are not always up to date, they are not automated. if docker images are used is equivalent for sure.
